[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.pytest_cache
  | \.vscode
  | gateway-service # Exclude Java/Gradle files
  | notebooks 
  | \.ipynb_checkpoints
)/
'''

[tool.ruff]
line-length = 100

[tool.ruff.lint]
# Ruff acts as a faster, all-in-one replacement for flake8, isort, etc.
select = ["E", "F", "I", "UP", "B"] 
ignore = ["E501"] # Ignore line length (let black handle it)

[tool.ruff.lint.per-file-ignores]
# Ignore type hints checks in test files
"tests/*" = ["D", "I", "ANN"]
"data-pipeline/src/feature_engineering.py" = ["F401"] # Allow unused imports initially 
"**/*.ipynb" = ["F401", "F841", "I001"] 